;----------------------------------------------
;  ram.i
;----------------------------------------------

;-------------------------------------------------------------------------------------------------------
; LABEL       ADDRESS        DESCRIPTION
;-------------------------------------------------------------------------------------------------------
ADRAY1       = $03   ;-04     JUMP VECTOR: CONVERT FAC TO INTEGER IN (A/Y) ($B1AA).
ADRAY2       = $05   ;-06     JUMP VECTOR: CONVERT INTEGER IN (A/Y) TO FLOATING POINT IN (FAC); ($B391).
CHARAC       = $07   ;        SEARCH CHARACTER/TEMPORARY INTEGER DURING INT.
ENDCHR       = $08   ;        FLAG: SCAN FOR QUOTE AT END OF STRING.
INTEGR       = $07   ;-08     TEMPORARY INTEGER DURING OR/AND.
TRMPOS       = $09   ;        SCREEN COLUMN FOR LAST TAB.
VERCK        = $0A   ;        FLAG: 0 = LOAD, 1 = VERIFY.
COUNT        = $0B   ;        INPUT BUFFER POINTER/NUMBER OF SUBSCRIPTS.
DIMFLG       = $0C   ;        FLAG: DEFAULT ARRAY DIMENSION.
VALTYP       = $0D   ;        DATA TYPE FLAG: $00 = NUMERIC, $FF = STRING.
INTFLG       = $0E   ;        DATA TYPE FLAG: $00 = FLOATING POINT, $80 = INTEGER.
GARBFL       = $0F   ;        FLAG: DATA SCAN/LIST QUOTE/GARBAGE COLLECTION.
SUBFLG       = $10   ;        FLAG: SUBSCRIPT REFERENCE/USER FUNCTION CALL.
INPFLG       = $11   ;        INPUT FLAG: $00 = INPUT, $40 = GET, $98 = READ.
TANSGN       = $12   ;        FLAG: TAN SIGN/COMPARATIVE RESULT.
CHANNL       = $13   ;        FILE NUMBER OF CURRENT INPUT DEVICE.
LINNUM       = $14   ;-15     TEMPORARY: INTEGER VALUE.
TEMPPT       = $16   ;        POINTER: TEMPORARY STRING STACK.
LASTPT       = $17   ;-18     LAST TEMPORARY STRING ADDRESS.
TEMPST       = $19   ;-21     STACK FOR TEMPORARY STRINGS.
INDEX        = $22   ;-25     UTILITY POINTER AREA.
INDEX1       = $22   ;-23     FIRST UTILITY POINTER.
INDEX2       = $24   ;-25     SECOND UTILITY POINTER.
RESHO        = $26   ;-2A     FLOATING POINT PRODUCT OF MULTIPLY AND DIVIDE.
TXTTAB       = $2B   ;-2C     POINTER: START OF BASIC TEXT AREA ($0801).
VARTAB       = $2D   ;-2E     POINTER: START OF BASIC VARIABLES.
ARYTAB       = $2F   ;-30     POINTER: START OF BASIC ARRAYS.
STREND       = $31   ;-32     POINTER: END OF BASIC ARRAYS + 1.
FRETOP       = $33   ;-34     POINTER: BOTTOM OF STRING SPACE.
FRESPC       = $35   ;-36     UTILITY STRING POINTER.
BASSIZ       = $37   ;-38     POINTER: HIGHEST ADDRESS AVAILABLE TO BASIC ($A000).
CURLIN       = $39   ;-3A     CURRENT BASIC LINE NUMBER.
OLDLIN       = $3B   ;-3C     PREVIOUS BASIC LINE NUMBER.
OLDTXT       = $3D   ;-3E     POINTER: BASIC STATEMENT FOR CONT.
DATLIN       = $3F   ;-40     CURRENT DATA LINE NUMBER.
DATPTR       = $41   ;-42     POINTER: USED BY READ - CURRENT DATA ITEM ADDRESS.
INPPTR       = $43   ;-44     POINTER: TEMPORARY STORAGE OF POINTER DURING INPUT ROUTINE.
VARNAM       = $45   ;-46     NAME OF VARIABLE BEING SOUGHT IN VARIABLE TABLE.
VARPNT       = $47   ;-48     POINTER: TO VALUE OF (VARNAM) IF INTEGER, TO DESCRIPTOR IF STRING.
FORPNT       = $49   ;-4A     POINTER: INDEX VARIABLE FOR FOR/NEXT LOOP.
VARTXT       = $4B   ;-4C     TEMPORARY STORAGE FOR TXTPTR DURING READ, INPUT AND GET.
OPMASK       = $4D   ;        MASK USED DURING FRMEVL.
TEMPF3       = $4E   ;-52     TEMPORARY STORAGE FOR FLPT VALUE.
FOUR6        = $53   ;        LENGTH OF STRING VARIABLE DURING GARBEGE COLLECTION.
JMPER        = $54   ;-56     JUMP VECTOR USED IN FUNCTION EVALUATION - JMP FOLLOWED BY ADDRESS ($4C,$LB,$MB).
TEMPF1       = $57   ;-5B     TEMPORARY STORAGE FOR FLPT VALUE.
TEMPF2       = $5C   ;-60     TEMPORARY STORAGE FOR FLPT VALUE.
FAC          = $61   ;-66     MAIN FLOATING POINT ACCUMULATOR.
FACEXP       = $61   ;        FAC EXPONENT.
FACHO        = $62   ;-65     FAC MANTISSA.
FACSGN       = $66   ;        FAC SIGN.
SGNFLG       = $67   ;        POINTER: SERIES EVALUATION CONSTANT.
BITS         = $68   ;        BIT OVERFLOW AREA DURING NORMALISATION ROUTINE.
AFAC         = $69   ;-6E     AUXILIARY FLOATING POINT ACCUMULATOR.
ARGEXP       = $69   ;        AFAC EXPONENT.
ARGHO        = $6A   ;-6D     AFAC MANTISSA.
ARGSGN       = $6E   ;        AFAC SIGN.
ARISGN       = $6F   ;        SIGN OF RESULT OF ARITHMETIC EVALUATION.
FACOV        = $70   ;        FAC LOW-ORDER ROUNDING.
FBUFPT       = $71   ;-72     POINTER: USED DURING CRUNCH/ASCII CONVERSION.
CHRGET       = $73   ;-8A     SUBROUTINE: GET NEXT BYTE OF BASIC TEXT.
CHRGOT       = $79   ;        ENTRY TO GET SAME BYTE AGAIN.
TXTPTR       = $7A   ;-7B     POINTER: CURRENT BYTE OF BASIC TEXT.
RNDX         = $8B   ;-8F     FLOATING RND FUNCTION SEED VALUE.
STATUS       = $90   ;        KERNAL I/O STATUS WORD  ST.
STKEY        = $91   ;        FLAG: $7F = STOP KEY.
SVXT         = $92   ;        TIMING CONSTANT FOR TAPE.
VERCKK       = $93   ;        FLAG: 0 = LOAD, 1 = VERIFY.
C3PO         = $94   ;        FLAG: SERIAL BUS - OUTPUT CHARACTER BUFFERED.
BSOUR        = $95   ;        BUFFERED CHARACTER FOR SERIAL BUS.
SYNO         = $96   ;        CASSETTE SYNC. NUMBER.
TEMPX        = $97   ;        TEMPORARY STORAGE OF X REGISTER DURING CHRIN.
TEMPY        = $97   ;        TEMPORARY STORAGE OF Y REGISTER DURING RS232 FETCH.
LDTND        = $98   ;        NUMBER OF OPEN FILES/INDEX TO FILE TABLE.
DFLTN        = $99   ;        DEFAULT INPUT DEVICE (0).
DFLTO        = $9A   ;        DEFAULT OUTPUT DEVICE (3).
PRTY         = $9B   ;        PARITY OF BYTE OUTPUT TO TAPE.
DPSW         = $9C   ;        FLAG: BYTE RECEIVED FROM TAPE.
MSGFLG       = $9D   ;        FLAG: $00 = PROGRAM MODE: SUPPRESS ERROR
                     ;        MESSAGES, $40 = KERNAL ERROR MESSAGES ONLY,
                     ;        $80 = DIRECT MODE: FULL ERROR MESSAGES.
FNMIDX       = $9E   ;        INDEX TO CASSETTE FILE NAME/HEADER ID FOR TAPE WRITE.
PTR1         = $9E   ;        TAPE ERROR LOG PASS 1.
PTR2         = $9F   ;        TAPE ERROR LOG PASS 2.
TIME         = $A0   ;-A2     REAL-TIME JIFFY CLOCK (UPDATED BY IRQ
                     ;        INTERRUPT APPROX. EVERY 1/60 OF SECOND);
                     ;        UPDATE ROUTINE: UDTIMK ($F69B).
TSFCNT       = $A3   ;        BIT COUNTER TAPE READ OR WRITE/SERIAL BUS EOI (END OF INPUT) FLAG.
TBTCNT       = $A4   ;        PULSE COUNTER TAPE READ OR WRITE/SERIAL BUS SHIFT COUNTER.
CNTDN        = $A5   ;        TAPE SYNCHRONISING COUNT DOWN.
BUFPNT       = $A6   ;        POINTER: TAPE I/O BUFFER.
INBIT        = $A7   ;        RS232 TEMPORARY FOR RECEIVED BIT/TAPE TEMPORARY.
BITC1        = $A8   ;        RS232 INPUT BIT COUNT/TAPE TEMPORARY.
RINONE       = $A9   ;        RS232 FLAG: START BIT CHECK/TAPE TEMPORARY.
RIDATA       = $AA   ;        RS232 INPUT BYTE BUFFER/TAPE TEMPORARY.
RIPRTY       = $AB   ;        RS232 INPUT PARITY/TAPE TEMPORARY.
SAL          = $AC   ;-AD     POINTER: TAPE BUFFER/SCREEN SCROLLING.
EAL          = $AE   ;-AF     TAPE END ADDRESS/END OF PROGRAM.
CMPO         = $B0   ;-B1     TAPE TIMING CONSTANTS.
TAPE1        = $B2   ;-B3     POINTER: START ADDRESS OF TAPE BUFFER ($033C).
BITTS        = $B4   ;        RS232 WRITE BIT COUNT/TAPE READ TIMING FLAG.
NXTBIT       = $B5   ;        RS232 NEXT BIT TO SEND/TAPE READ - END OF TAPE.
RODATA       = $B6   ;        RS232 OUTPUT BYTE BUFFER/TAPE READ ERROR FLAG.
FNLEN        = $B7   ;        NUMBER OF CHARACTERS IN FILENAME.
LA           = $B8   ;        CURRENT FILE - LOGICAL FILE NUMBER.
SA           = $B9   ;        CURRENT FILE - SECONDARY ADDRESS.
FA           = $BA   ;        CURRENT FILE - FIRST ADDRESS (DEVICE NUMBER).
                     ;          OPEN LA,FA,SA;  OPEN 1,8,15,"I0":CLOSE 1
FNADR        = $BB   ;-BC     POINTER: CURRENT FILE NAME ADDRESS.
ROPRTY       = $BD   ;        RS232 OUTPUT PARITY/TAPE BYTE TO BE INPUT OR OUTPUT.
FSBLK        = $BE   ;        TAPE INPUT/OUTPUT BLOCK COUNT.
MYCH         = $BF   ;        SERIAL WORD BUFFER.
CAS1         = $C0   ;        TAPE MOTOR SWITCH.
STAL         = $C1   ;-C2     START ADDRESS FOR LOAD AND CASSETTE WRITE.
MEMUSS       = $C3   ;-C4     POINTER: TYPE 3 TAPE LOAD AND GENERAL USE.
LSTX         = $C5   ;        MATRIX VALUE OF LAST KEY PRESSED; NO KEY = $40.
NDX          = $C6   ;        NUMBER OF CHARACTERS IN KEYBOARD BUFFER QUEUE.
RVS          = $C7   ;        FLAG: REVERSE ON/OFF; ON = $01, OFF = $00.
INDX         = $C8   ;        POINTER: END OF LINE FOR INPUT (USED TO SUPPRESS TRAILING SPACES).
LXSP         = $C9   ;-CA     CURSOR X/Y (LINE/COLUMN) POSITION AT START OF INPUT.
SFDX         = $CB   ;        FLAG: PRINT SHIFTED CHARACTERS.
BLNSW        = $CC   ;        FLAG: CURSOR BLINK; $00 = ENABLED, $01 = DISABLED.
BLNCT        = $CD   ;        TIMER: COUNT DOWN FOR CURSOR BLINK TOGGLE.
GDBLN        = $CE   ;        CHARACTER UNDER CURSOR WHILE CURSOR INVERTED.
BLNON        = $CF   ;        FLAG: CURSOR STATUS; $00 = OFF, $01 = ON.
CRSW         = $D0   ;        FLAG: INPUT FROM SCREEN = $03, OR KEYBOARD = $00.
PNT          = $D1   ;-D2     POINTER: CURRENT SCREEN LINE ADDRESS.
PNTR         = $D3   ;        CURSOR COLUMN ON CURRENT LINE, INCLUDING WRAP-ROUND LINE, IF ANY.
QTSW         = $D4   ;        FLAG: EDITOR IN QUOTE MODE; $00 = NOT.
LNMX         = $D5   ;        CURRENT LOGICAL LINE LENGTH: 39 OR 79.
TBLX         = $D6   ;        CURRENT SCREEN LINE NUMBER OF CURSOR.
SCHAR        = $D7   ;        SCREEN VALUE OF CURRENT INPUT CHARACTER/LAST CHARACTER OUTPUT.
INSRT        = $D8   ;        COUNT OF NUMBER OF INSERTS OUTSTANDING.
LDTB1        = $D9   ;-F2     SCREEN LINE LINK TABLE/EDITOR TEMPORARIES.
                     ;        HIGH BYTE OF LINE SCREEN MEMORY LOCATION.
USER         = $F3   ;-F4     POINTER: CURRENT COLOUR RAM LOCATION.
KEYTAB       = $F5   ;-F6     VECTOR: CURRENT KEYBOARD DECODING TABLE. ($EB81)
RIBUF        = $F7   ;-F8     RS232 INPUT BUFFER POINTER.
ROBUF        = $F9   ;-FA     RS232 OUTPUT BUFFER POINTER.
FREKZP       = $FB   ;-FE     FREE ZERO PAGE SPACE FOR USER PROGRAMS.
BASZPT       = $FF   ;        BASIC TEMPORARY DATA AREA.
ASCWRK       = $FF   ;-010A   ASSEMBLY AREA FOR FLOATING POINT TO ASCII CONVERSION.
BAD          = $0100 ;-013E   TAPE INPUT ERROR LOG.
STACK        = $0100 ;-01FF   6510 HARDWARE STACK AREA.
BSTACK       = $013F ;-01FF   BASIC STACK AREA.
BUF          = $0200 ;-0258   BASIC INPUT BUFFER (INPUT LINE FROM SCREEN).
LAT          = $0259 ;-0262   KERNAL TABLE: ACTIVE LOGICAL FILE NUMBERS.
FAT          = $0263 ;-026C   KERNAL TABLE: ACTIVE FILE FIRST ADDRESSES (DEVICE NUMBERS).
SAT          = $026D ;-0276   KERNAL TABLE: ACTIVE FILE SECONDARY ADDRESSES.
KEYD         = $0277 ;-0280   KEYBOARD BUFFER QUEUE (FIFO).
MEMSTR       = $0281 ;-0282   POINTER: BOTTOM OF MEMORY FOR OPERATING SYSTEM ($0800).
MEMSIZ       = $0283 ;-0284   POINTER: TOP OF MEMORY FOR OPERATING SYSTEM ($A000).
TIMOUT       = $0285 ;        SERIAL IEEE BUS TIMEOUT DEFEAT FLAG.
CHRCOL       = $0286 ;        CURRENT CHARACTER COLOUR CODE.
GDCOL        = $0287 ;        BACKGROUND COLOUR UNDER CURSOR.
HIBASE       = $0288 ;        HIGH BYTE OF SCREEN MEMORY ADDRESS ($04).
XMAX         = $0289 ;        MAXIMUM NUMBER OF BYTES IN KEYBOARD BUFFER ($0A).
RPTFLG       = $028A ;        FLAG: REPEAT KEYS; $00 = CURSORS, INST/DEL & SPACE REPEAT,
                     ;                           $40 NO KEYS REPEAT,
                     ;                           $80 ALL KEYS REPEAT ($00).
KOUNT        = $028B ;        REPEAT KEY: SPEED COUNTER ($04).
DELAY        = $028C ;        REPEAT KEY: FIRST REPEAT DELAY COUNTER ($10).
SHFLAG       = $028D ;        FLAG: SHIFT KEYS: BIT 1 = SHIFT, BIT 2 = CBM,
                     ;        BIT 3 = CTRL; ($00 = NONE, $01 = SHIFT, ETC.).
LSTSHF       = $028E ;        LAST SHIFT KEY USED FOR DEBOUNCING.
KEYLOG       = $028F ;-0290   VECTOR: ROUTINE TO DETERMINE KEYBOARD TABLE
                     ;        TO USE BASED ON SHIFT KEY PATTERN ($EB48).
MODE         = $0291 ;        FLAG: UPPER/LOWER CASE CHANGE: $00 = DISABLED, $80 = ENABLED ($00).
AUTODN       = $0292 ;        FLAG: AUTO SCROLL DOWN: $00 = DISABLED ($00).
M51CTR       = $0293 ;        RS232 PSEUDO 6551 CONTROL REGISTER IMAGE.
M51CDR       = $0294 ;        RS232 PSEUDO 6551 COMMAND REGISTER IMAGE.
M51AJB       = $0295 ;-0296   RS232 NON-STANDARD BITS/SECOND.
RSSTAT       = $0297 ;        RS232 PSEUDO 6551 STATUS REGISTER IMAGE.
BITNUM       = $0298 ;        RS232 NUMBER OF BITS LEFT TO SEND.
BAUDOF       = $0299 ;-029A   RS232 BAUD RATE; FULL BIT TIME MICROSECONDS.
RIDBE        = $029B ;        RS232 INDEX TO END OF INPUT BUFFER.
RIDBS        = $029C ;        RS232 POINTER: HIGH BYTE OF ADDRESS OF INPUT BUFFER.
RODBS        = $029D ;        RS232 POINTER: HIGH BYTE OF ADDRESS OF OUTPUT BUFFER.
RODBE        = $029E ;        RS232 INDEX TO END OF OUTPUT BUFFER.
IRQTMP       = $029F ;-02A0   TEMPORARY STORE FOR IRQ VECTOR DURING TAPE OPERATIONS.
ENABL        = $02A1 ;        RS232 ENABLES.
TODSNS       = $02A2 ;        TOD SENSE DURING TAPE I/O.
TRDTMP       = $02A3 ;        TEMPORARY STORAGE DURING TAPE READ.
TD1IRQ       = $02A4 ;        TEMPORARY D1IRQ INDICATOR DURING TAPE READ.
TLNIDX       = $02A5 ;        TEMPORARY FOR LINE INDEX.
TVSFLG       = $02A6 ;        FLAG: TV STANDARD: $00 = NTSC, $01 = PAL.
IERROR       = $0300 ;-0301   VECTOR: INDIRECT ENTRY TO BASIC ERROR MESSAGE, (X) POINTS TO MESSAGE ($E38B).
IMAIN        = $0302 ;-0303   VECTOR: INDIRECT ENTRY TO BASIC INPUT LINE AND DECODE ($A483).
ICRNCH       = $0304 ;-0305   VECTOR: INDIRECT ENTRY TO BASIC TOKENISE ROUTINE ($A57C).
IQPLOP       = $0306 ;-0307   VECTOR: INDIRECT ENTRY TO BASIC LIST ROUTINE ($A71A).
IGONE        = $0308 ;-0309   VECTOR: INDIRECT ENTRY TO BASIC CHARACTER DISPATCH ROUTINE ($A7E4).
IEVAL        = $030A ;-030B   VECTOR: INDIRECT ENTRY TO BASIC TOKEN EVALUATION ($AE86).
SAREG        = $030C ;        STORAGE FOR 6510 ACCUMULATOR DURING SYS.
SXREG        = $030D ;        STORAGE FOR 6510 X-REGISTER DURING SYS.
SYREG        = $030E ;        STORAGE FOR 6510 Y-REGISTER DURING SYS.
SPREG        = $030F ;        STORAGE FOR 6510 STATUS REGISTER DURING SYS.
USRPOK       = $0310 ;        USR FUNCTION JMP INSTRUCTION ($4C).
USRADD       = $0311 ;-0312   USR ADDRESS ($LB,$MB).
CINV         = $0314 ;-0315   VECTOR: HARDWARE IRQ INTERRUPT ADDRESS ($EA31).
CBINV        = $0316 ;-0317   VECTOR: BRK INSTRUCTION INTERRUPT ADDRESS ($FE66).
NMINV        = $0318 ;-0319   VECTOR: HARDWARE NMI INTERRUPT ADDRESS ($FE47).
IOPEN        = $031A ;-031B   VECTOR: INDIRECT ENTRY TO KERNAL OPEN ROUTINE ($F34A).
ICLOSE       = $031C ;-031D   VECTOR: INDIRECT ENTRY TO KERNAL CLOSE ROUTINE ($F291).
ICHKIN       = $031E ;-031F   VECTOR: INDIRECT ENTRY TO KERNAL CHKIN ROUTINE ($F20E).
ICKOUT       = $0320 ;-0321   VECTOR: INDIRECT ENTRY TO KERNAL CHKOUT ROUTINE ($F250).
ICLRCH       = $0322 ;-0323   VECTOR: INDIRECT ENTRY TO KERNAL CLRCHN ROUTINE ($F333).
IBASIN       = $0324 ;-0325   VECTOR: INDIRECT ENTRY TO KERNAL CHRIN ROUTINE ($F157).
IBSOUT       = $0326 ;-0327   VECTOR: INDIRECT ENTRY TO KERNAL CHROUT ROUTINE ($F1CA).
ISTOP        = $0328 ;-0329   VECTOR: INDIRECT ENTRY TO KERNAL STOP ROUTINE ($F6ED).
IGETIN       = $032A ;-032B   VECTOR: INDIRECT ENTRY TO KERNAL GETIN ROUTINE ($F13E).
ICLALL       = $032C ;-032D   VECTOR: INDIRECT ENTRY TO KERNAL CLALL ROUTINE ($F32F).
USRCMD       = $032E ;-032F   USER DEFINED VECTOR ($FE66).
ILOAD        = $0330 ;-0331   VECTOR: INDIRECT ENTRY TO KERNAL LOAD ROUTINE ($F4A5).
ISAVE        = $0332 ;-0333   VECTOR: INDIRECT ENTRY TO KERNAL SAVE ROUTINE ($F5ED).
TBUFFR       = $033C ;-03FB   TAPE I/O BUFFER.
VICSCN       = $0400 ;-07E7   DEFAULT SCREEN VIDEO MATRIX.
SPNTRS       = $07F8 ;-07FF   DEFAULT SPRITE DATA POINTERS.
